# Playbook to use register to output data from a file and use as a variable
---
- name: Use Register
  hosts: webservers
# Uses the vars/common to pull common variables
  vars_files: vars/common
  tasks:

  - name: Run Shell
    shell: cat /etc/passwd
    register: passwd_contents
  - name: Run Debug
    debug:
# Stores the output of /etc/passwd into a variable called passwd_contents.  debug will render the outputr to the screen fore the admin to view the results
      var: "passwd_contents"
...
