# Playbook to use blocks with a when statement when installing Apache on RHEL
---
- name: Install Apache2 on RHEL Servers
  hosts: webservers
  vars_files: 
    - vars/common
  tasks:
 
  - name: Set up httpd package
    block:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: restart httpd
      service:
        name: httpd
        state: restarted
# When and Block are at the same level, BLock looks at the when statement before executing.
    when: ansible_distribution == "Debian"
...
