# This will deploy a lamp stack (Linux Apache, MariaDB, PHP Server) "Note: must have firewalld disabled for this exercise"
---
- name: Deploy LAMP Server to Managed Node
    hosts: webservers
    remote_user: ansible
    become: yes
    
    tasks:
    - name: Install Apache Server
        yum: name=https
             state=latest
        tags:
        - installapache
        
    - name: Start Apache Server
        service: 
            name=https
            state=started 
        tags:
        - startapache
        
    - name: Install MariaDB Server
        yum: name=[mariadb-server, mariadb-devel, mariadb-connector-odbc, mariadb-server-utils, python3-pymysql, php]
             state=latest
        tags:
        - installmariadb
        
    - name: Start MariaDB Service
        service: 
            name=mariadb
            state=started
        tags:
        - startmariadb
        
    - name: Update MariaDB Root Password
        mysql_user: 
            name: root
            host: localhost
            password: mysql
            login_user: root
            check_implicit_admin: yes
            priv: "*.*:ALL,GRANT"
        tags:
        - configdb          
               
    - name: Create a new Database called Inventory
        mysql_db: 
            name=inventory
            state=present
            login_user=root
            login_password=mysql
        tags:
        - createdb        
               
    - name: Copy SQL File
        copy: 
            src=/source/servers.sql
            dest=/tmp/servers.sql
        tags:
        - copysql 
               
    - name: Create Table with Data
        shell: mysql -u root -p mysql < /tmp/servers.sql
        tags:
        - createtable

    - name: Copy PHP File
        copy: src=/source/connection.php dest=/var/www/html/

    - name: Copy Index PHP File
        copy: src=/source/index.php dest=/var/www/html/
        tags:
        - copyfiles
            
    - name: Restart httpd service
        service: 
            name=httpd
            state=restarted
        tags:
        - restartapache             
...
