#
---
- hosts: esxi_servers
  connection: local
  gather_facts: true

  vars_files:
    - vars/main

    change_hostname: false
    ntp_state: present

  roles:
    - esxi-host-config
    - esxi-adv-settings
    - esxi-services
    - esxi-vmk-interfaces
