---
# tasks file for motd
- name: copy motd file
  template:
    src: templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0444

- name: verify motd file
  command: cat /etc/motd
  register: answer

- name: spit out answer
  debug:
    var: answer.stdout
...
